# =================================
# ======== Default Profile ========
# =================================
[profile.default]
verbosity = 3
solc_version = "0.8.16"
optimizer = true
optimizer_runs = 10_000_000
remappings = ["test/=test/", "script/=script/"]

# ==============================
# ======== Lite Profile ========
# ==============================
# Speed up compilation and tests during development.

[profile.lite]
optimizer = false

[profile.lite.fuzz]
runs = 50

[profile.lite.invariant]
runs = 10

# ============================
# ======== CI Profile ========
# ============================
[profile.ci.fuzz]
runs = 5000

[profile.ci.invariant]
runs = 1000

# ============================
# ======== Formatting ========
# ============================
[fmt]
bracket_spacing = false
int_types = 'short'
line_length = 80
multiline_func_header = 'attributes_first'
number_underscore = 'thousands'
quote_style = 'double'
single_line_statement_blocks = 'single'
tab_width = 2